### ISSUE TITLE
Get-CertificateTemplate and setting CT_FLAG_SUBJECT_ALT_REQUIRE_SPN

### ISSUE THREAD

**Issue by NickyGr** [PKISolutions/PSPKI#122] opened 2020-10-05 13:28 UTC
PSversion: 5.1.14393.0
PSPKIversion: 3.7.2

Dear PSPKI team,
i've set up a CA Template with CT_FLAG_SUBJECT_ALT_REQUIRE_SPN enabled.
When i run Get-CertificateTemplate it doesn't display a "normalized" Value on Settings->SubjectName like e.g when CT_FLAG_SUBJECT_ALT_REQUIRE_UPN is enabled. Instead the value 8388608 of the flag is displayed instead of something readable like: Subjectname: AltSubjectRequireSPN

Also when CT_FLAG_SUBJECT_ALT_REQUIRE_SPN is enabled and another setting is also enabled on Subject Name Tab the "non-normalized" **sum** value of all enabled settings in Subject Name tab is displayed.

Thank you in advance for your time,
N.

Source for the SubjectNameFlags:
https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/certreq_1

**Comment by Crypt32** [comment] 2020-10-05 13:42
I can confirm this issue and I have to address this issue to Microsoft since they don't have updated relevant documentation I use as trusted source.

**Comment by Crypt32** [comment] 2023-06-15 07:39
Fixed in [v4.0.0](https://github.com/PKISolutions/PSPKI/releases/tag/v4.0.0)

**Closed by Crypt32** 2023-06-15 07:39 UTC
Labels: bug, fixed-vNext
