### ISSUE TITLE
Cannot get issued request

### ISSUE THREAD

**Issue by andy968** [PKISolutions/PSPKI#118] opened 2020-09-22 11:33 UTC
I've just installed this module. 

Get-CertificationAuthority works and returns the CA (although it returns two identical entries) however when trying to pipe it into Get-IssuedRequest I get the following:

Get-AdcsDatabaseRow : Exception calling "GetDbReader" with "1" argument(s): "CCertView::OpenConnection: The parameter is incorrect. 0x80070057 (WIN32: 87 ERROR_INVALID_PARAMETER)"

Any idea what this might be? Many thanks

**Comment by Crypt32** [comment] 2020-09-22 12:17
For some reasons connection to CA database cannot be opened. This can be a firewall or permissions issue. Interesting, where you get two identical entries.

**Comment by andy968** [comment] 2020-09-22 12:23
I have tried running the command both locally on the Subordinate CA and remotely on another machine in the same domain

**Comment by Crypt32** [comment] 2020-09-22 12:46
can you show what `Get-CertificationAuthority` returns? I'm more interested in `ConfigString` property.

**Comment by andy968** [comment] 2020-09-22 13:02
Below is the anonymised output

`Name                 : CA0
DisplayName          : CA0
ComputerName         : CA0.domain.com
ConfigString         : CA0.domain.com\CA0
DistinguishedName    : CN=CA0,CN=Enrollment Services,CN=Public Key Services,CN=Services,CN=Configuration,DC=domain,DC=com
Type                 : Enterprise Subordinate CA
IsEnterprise         : True
IsRoot               : False
OperatingSystem      : Microsoft Windows Server 2012 R2 Standard
IsAccessible         : True
RegistryOnline       : True
ServiceStatus        : Running
SetupStatus          : ServerInstall, ClientInstall, SecurityUpgraded, ServerIsUptoDate
Certificate          : System.Security.Cryptography.X509Certificates.X509Certificate2
BaseCRL              : 
DeltaCRL             : 
EnrollmentServiceURI : 
EnrollmentEndpoints  : {https://ca0.domain.com/CA0_CES_Kerberos/service.svc/CES}

Name                 : CA0
DisplayName          : CA0
ComputerName         : CA0.domain.com
ConfigString         : CA0.domain.com\CA0
DistinguishedName    : CN=CA0,CN=Enrollment Services,CN=Public Key Services,CN=Services,CN=Configuration,DC=domain,DC=com
Type                 : Enterprise Subordinate CA
IsEnterprise         : True
IsRoot               : False
OperatingSystem      : Microsoft Windows Server 2012 R2 Standard
IsAccessible         : True
RegistryOnline       : True
ServiceStatus        : Running
SetupStatus          : ServerInstall, ClientInstall, SecurityUpgraded, ServerIsUptoDate
Certificate          : System.Security.Cryptography.X509Certificates.X509Certificate2
BaseCRL              : 
DeltaCRL             : 
EnrollmentServiceURI : 
EnrollmentEndpoints  : {https://ca0.domain.com/CA0_CES_Kerberos/service.svc/CES}`

**Comment by Crypt32** [comment] 2020-09-22 13:09
does `certutil -view` work for you? What happens if do `Connect-CA -ComputerName "CA0" | Get-IssuedRequest`?

**Comment by andy968** [comment] 2020-09-22 13:12
`PS C:\Users\user> certutil -view
CertUtil: -view command FAILED: 0x80070057 (WIN32: 87 ERROR_INVALID_PARAMETER)
CertUtil: The parameter is incorrect.`

And the Connect-CA produces the same error as I posted in the first comment

Thanks

**Comment by Crypt32** [comment] 2020-09-22 13:25
If certutil fails for you, then there is something wrong with your CA database. It can be broken or in corrupt state. You can additionally confirm it with Certification Authority MMC snap-in. Have you tried to restart CA, or reboot the server?

**Comment by andy968** [comment] 2020-09-22 13:41
Certification Authority management console is running fine and the server is issuing certs. I've tried restarting CA and restarting the server and it hasn't made a difference

**Comment by Crypt32** [comment] 2022-06-18 19:19
Closing since it is reproducible by certutil, thus not an issue in PSPKI code

**Closed by Crypt32** 2022-06-18 19:19 UTC
